

service: talkclass

provider:
  name: aws
  runtime: python2.7

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true

functions:
  hello:
    handler: handler.handler
    environment:
      hello: 'Hola Randall'
